// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.12.4
// source: proto/leads.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AddLeadRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name   string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Email  string `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Phone  string `protobuf:"bytes,3,opt,name=phone,proto3" json:"phone,omitempty"`
	Status string `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
}

func (x *AddLeadRequest) Reset() {
	*x = AddLeadRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_leads_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddLeadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddLeadRequest) ProtoMessage() {}

func (x *AddLeadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_leads_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddLeadRequest.ProtoReflect.Descriptor instead.
func (*AddLeadRequest) Descriptor() ([]byte, []int) {
	return file_proto_leads_proto_rawDescGZIP(), []int{0}
}

func (x *AddLeadRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AddLeadRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *AddLeadRequest) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *AddLeadRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type AddLeadResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *AddLeadResponse) Reset() {
	*x = AddLeadResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_leads_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddLeadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddLeadResponse) ProtoMessage() {}

func (x *AddLeadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_leads_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddLeadResponse.ProtoReflect.Descriptor instead.
func (*AddLeadResponse) Descriptor() ([]byte, []int) {
	return file_proto_leads_proto_rawDescGZIP(), []int{1}
}

func (x *AddLeadResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type UpdateLeadStatusRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Email     string `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	NewStatus string `protobuf:"bytes,2,opt,name=new_status,json=newStatus,proto3" json:"new_status,omitempty"`
}

func (x *UpdateLeadStatusRequest) Reset() {
	*x = UpdateLeadStatusRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_leads_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateLeadStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateLeadStatusRequest) ProtoMessage() {}

func (x *UpdateLeadStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_leads_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateLeadStatusRequest.ProtoReflect.Descriptor instead.
func (*UpdateLeadStatusRequest) Descriptor() ([]byte, []int) {
	return file_proto_leads_proto_rawDescGZIP(), []int{2}
}

func (x *UpdateLeadStatusRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *UpdateLeadStatusRequest) GetNewStatus() string {
	if x != nil {
		return x.NewStatus
	}
	return ""
}

type UpdateLeadStatusResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *UpdateLeadStatusResponse) Reset() {
	*x = UpdateLeadStatusResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_leads_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateLeadStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateLeadStatusResponse) ProtoMessage() {}

func (x *UpdateLeadStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_leads_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateLeadStatusResponse.ProtoReflect.Descriptor instead.
func (*UpdateLeadStatusResponse) Descriptor() ([]byte, []int) {
	return file_proto_leads_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateLeadStatusResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_proto_leads_proto protoreflect.FileDescriptor

var file_proto_leads_proto_rawDesc = []byte{
	0x0a, 0x11, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x6c, 0x65, 0x61, 0x64, 0x73, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x05, 0x6c, 0x65, 0x61, 0x64, 0x73, 0x22, 0x68, 0x0a, 0x0e, 0x41, 0x64,
	0x64, 0x4c, 0x65, 0x61, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x12, 0x14, 0x0a, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x68, 0x6f, 0x6e, 0x65, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x70, 0x68, 0x6f, 0x6e, 0x65, 0x12, 0x16, 0x0a, 0x06,
	0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x22, 0x2b, 0x0a, 0x0f, 0x41, 0x64, 0x64, 0x4c, 0x65, 0x61, 0x64, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x22, 0x4e, 0x0a, 0x17, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x4c, 0x65, 0x61, 0x64, 0x53,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05,
	0x65, 0x6d, 0x61, 0x69, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x6d, 0x61,
	0x69, 0x6c, 0x12, 0x1d, 0x0a, 0x0a, 0x6e, 0x65, 0x77, 0x5f, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x6e, 0x65, 0x77, 0x53, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x22, 0x34, 0x0a, 0x18, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x4c, 0x65, 0x61, 0x64, 0x53,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a,
	0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
	0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x32, 0x9d, 0x01, 0x0a, 0x0c, 0x4c, 0x65, 0x61, 0x64,
	0x73, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x38, 0x0a, 0x07, 0x41, 0x64, 0x64, 0x4c,
	0x65, 0x61, 0x64, 0x12, 0x15, 0x2e, 0x6c, 0x65, 0x61, 0x64, 0x73, 0x2e, 0x41, 0x64, 0x64, 0x4c,
	0x65, 0x61, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x6c, 0x65, 0x61,
	0x64, 0x73, 0x2e, 0x41, 0x64, 0x64, 0x4c, 0x65, 0x61, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x53, 0x0a, 0x10, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x4c, 0x65, 0x61, 0x64,
	0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x1e, 0x2e, 0x6c, 0x65, 0x61, 0x64, 0x73, 0x2e, 0x55,
	0x70, 0x64, 0x61, 0x74, 0x65, 0x4c, 0x65, 0x61, 0x64, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1f, 0x2e, 0x6c, 0x65, 0x61, 0x64, 0x73, 0x2e, 0x55,
	0x70, 0x64, 0x61, 0x74, 0x65, 0x4c, 0x65, 0x61, 0x64, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x0d, 0x5a, 0x0b, 0x6c, 0x65, 0x61, 0x64, 0x73,
	0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_leads_proto_rawDescOnce sync.Once
	file_proto_leads_proto_rawDescData = file_proto_leads_proto_rawDesc
)

func file_proto_leads_proto_rawDescGZIP() []byte {
	file_proto_leads_proto_rawDescOnce.Do(func() {
		file_proto_leads_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_leads_proto_rawDescData)
	})
	return file_proto_leads_proto_rawDescData
}

var file_proto_leads_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_leads_proto_goTypes = []interface{}{
	(*AddLeadRequest)(nil),           // 0: leads.AddLeadRequest
	(*AddLeadResponse)(nil),          // 1: leads.AddLeadResponse
	(*UpdateLeadStatusRequest)(nil),  // 2: leads.UpdateLeadStatusRequest
	(*UpdateLeadStatusResponse)(nil), // 3: leads.UpdateLeadStatusResponse
}
var file_proto_leads_proto_depIdxs = []int32{
	0, // 0: leads.LeadsService.AddLead:input_type -> leads.AddLeadRequest
	2, // 1: leads.LeadsService.UpdateLeadStatus:input_type -> leads.UpdateLeadStatusRequest
	1, // 2: leads.LeadsService.AddLead:output_type -> leads.AddLeadResponse
	3, // 3: leads.LeadsService.UpdateLeadStatus:output_type -> leads.UpdateLeadStatusResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_leads_proto_init() }
func file_proto_leads_proto_init() {
	if File_proto_leads_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_leads_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddLeadRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_leads_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddLeadResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_leads_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateLeadStatusRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_leads_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateLeadStatusResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_leads_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_leads_proto_goTypes,
		DependencyIndexes: file_proto_leads_proto_depIdxs,
		MessageInfos:      file_proto_leads_proto_msgTypes,
	}.Build()
	File_proto_leads_proto = out.File
	file_proto_leads_proto_rawDesc = nil
	file_proto_leads_proto_goTypes = nil
	file_proto_leads_proto_depIdxs = nil
}
